# Profile information
name: Pa55w0rd
title: Pa55w0rd的博客
description: > # this means to ignore newlines until "baseurl:"
  记录生活、总结学习经验
keyword: "信息安全，Pa55w0rd, web安全, 企业安全"
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
encoding: utf-8

# 永久链接
permalink: /:year/:month/:day/:title/

# Social
facebook: #Add your Facebook
twitter: #Add your Twitter
google-plus: #Add your Google+
github: https://github.com/Pa55w0rd

# Contact form
email: pa55w0rd@aliyun.com

# 页脚
description_footer: 来自Pa55w0rd的博客！

# Comments
discus-identifier: # Add your Disqus identifier

# Search
search: true

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown

highlighter: pygments
 # url
category_dir: category/
tag_dir: tag/
  
# excerpt
excerpt_separator: "\n\n\n\n"  

gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
